// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package backend

import (
	"time"
)

type Chat struct {
	ID         string    `json:"id"`
	Senderid   User      `json:"senderid"`
	Receiverid User      `json:"receiverid"`
	Message    string    `json:"message"`
	CreatedAt  time.Time `json:"createdAt"`
}

type NewUser struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	Contactno string `json:"contactno"`
	Password  string `json:"password"`
}

type UpdateUser struct {
	Username  string `json:"username"`
	Email     string `json:"email"`
	Contactno string `json:"contactno"`
	Password  string `json:"password"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Contactno string `json:"contactno"`
	Password  string `json:"password"`
}
