// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package server2

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Email   string `json:"email"`
	Contact string `json:"contact"`
}
