// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package user

import (
	"time"
)

type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}
